### ISSUE TITLE
Multiple versions of nixpkgs

### ISSUE THREAD

**Issue by steve-chavez** [supabase/pg_net#106]
Currently we use [multiple versions of nixpkgs](https://github.com/supabase/pg_net/blob/9d3f5be9b90663fb1a6ba92df61698236e399363/shell.nix#L4-L18). There are some issues that prevents us from using only the newest nixpkgs.

https://github.com/supabase/pg_net/blob/9d3f5be9b90663fb1a6ba92df61698236e399363/shell.nix#L4-L18

## Tasks

- [x] newest nixpkgs is only python3
  - many tests give the `sqlalchemy.exc.ArgumentError: Textual SQL expression` error
  - cleared on https://github.com/supabase/pg_net/pull/107
- [ ] pathod command no longer exists https://github.com/mitmproxy/mitmproxy/issues/4273#issuecomment-1724490887. Ideally the maintainers reply with a way forward using `mitmproxy`.
- [x] newest openresty doesn't have a prefix option: https://github.com/supabase/pg_net/blob/9d3f5be9b90663fb1a6ba92df61698236e399363/shell.nix#L2-L3

This is not a big problem since we can keep using multiple versions. It only adds some extra time for building/testing - not too much time (only download time, not compile time) because https://cache.nixos.org/  is already populated.

**Comment by steve-chavez** [comment]
> pathod command no longer exists https://github.com/mitmproxy/mitmproxy/issues/4273#issuecomment-1724490887. Ideally the maintainers reply with a way forward using mitmproxy.

For the above the way forward is to have the same functionality on https://github.com/steve-chavez/ngx_pathological, then we can just use Nginx for the tests.
